package be.colardyn_it.model;
// Generated 26-nov-2012 19:32:06 by Hibernate Tools 3.4.0.CR1


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * ContestTag generated by hbm2java
 */
@Entity
@Table(name = "contest_tag")
public class ContestTag implements java.io.Serializable {


    private Integer id;
    private String tag;
    private String fullName;
    private String css;
    private Integer scheduleSortOrder;

    public ContestTag() {
    }


    public ContestTag(String tag) {
        this.tag = tag;
    }

    public ContestTag(String tag, String fullName, String css, Integer scheduleSortOrder) {
        this.tag = tag;
        this.fullName = fullName;
        this.css = css;
        this.scheduleSortOrder = scheduleSortOrder;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "id", nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    @Column(name = "tag", nullable = false, length = 20)
    public String getTag() {
        return this.tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }


    @Column(name = "full_name")
    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }


    @Column(name = "css", length = 30)
    public String getCss() {
        return this.css;
    }

    public void setCss(String css) {
        this.css = css;
    }


    @Column(name = "schedule_sort_order")
    public Integer getScheduleSortOrder() {
        return this.scheduleSortOrder;
    }

    public void setScheduleSortOrder(Integer scheduleSortOrder) {
        this.scheduleSortOrder = scheduleSortOrder;
    }


}


