package be.colardyn_it.model;

// Generated Jul 23, 2009 9:36:51 PM by Hibernate Tools 3.2.2.GA

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.ToString;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * ContestTeam generated by hbm2java
 */
@Entity
@Table(name = "contest_team", uniqueConstraints = @UniqueConstraint(columnNames = {"CONTEST_ID", "TEAM_ID"}))
@Builder
@ToString(doNotUseGetters = true)
@AllArgsConstructor
@NoArgsConstructor
public class ContestTeam implements java.io.Serializable {

    private Integer contestTeamId;
    private Team team;
    private Contest contest;

    public ContestTeam(Team team, Contest contest) {
        this.team = team;
        this.contest = contest;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "CONTEST_TEAM_ID", unique = true, nullable = false)
    public Integer getContestTeamId() {
        return this.contestTeamId;
    }

    public void setContestTeamId(Integer contestTeamId) {
        this.contestTeamId = contestTeamId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TEAM_ID", nullable = false)
    @NotNull
    public Team getTeam() {
        return this.team;
    }

    public void setTeam(Team team) {
        this.team = team;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CONTEST_ID", nullable = false)
    @NotNull
    public Contest getContest() {
        return this.contest;
    }

    public void setContest(Contest contest) {
        this.contest = contest;
    }

}
