package be.colardyn_it.model;

// Generated Apr 14, 2009 1:32:23 PM by Hibernate Tools 3.2.2.GA


import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.ToString;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Directx generated by hbm2java
 */
@Entity
@Table(name = "directx", uniqueConstraints = @UniqueConstraint(columnNames = "NAME"))
@Builder
@ToString(doNotUseGetters = true)
@AllArgsConstructor
@NoArgsConstructor
public class Directx implements java.io.Serializable {

    private Integer directxId;
    private String name;

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "DIRECTX_ID", unique = true, nullable = false)
    public Integer getDirectxId() {
        return this.directxId;
    }

    public void setDirectxId(Integer directxId) {
        this.directxId = directxId;
    }

    @Column(name = "NAME", unique = true, nullable = false, length = 30)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
