package be.colardyn_it.model;

// Generated Apr 14, 2009 1:43:35 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * MbModel generated by hbm2java
 */
@Entity
@Table(name = "disk_type")
public class DiskType implements java.io.Serializable {

    private Integer diskTypeId;
    private String name;

    public DiskType() {
    }

    public DiskType(String name) {
        this.name = name;
    }

    @Id()
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "DISK_TYPE_ID", unique = true, nullable = false)
    public Integer getDiskTypeId() {
        return this.diskTypeId;
    }

    public void setDiskTypeId(Integer diskTypeId) {
        this.diskTypeId = diskTypeId;
    }

    @Column(name = "NAME", nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
