package be.colardyn_it.model;

// Generated Apr 14, 2009 1:43:35 PM by Hibernate Tools 3.2.2.GA


import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.ToString;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * MbModel generated by hbm2java
 */
@Entity
@Table(name = "disk_productgroup")
@Builder
@ToString(doNotUseGetters = true, exclude = {"manufacturer","diskController","diskType"})
@AllArgsConstructor
@NoArgsConstructor
public class DiskProduct implements java.io.Serializable {

    private Integer groupId;
    private DiskController diskController;
    private Manufacturer manufacturer;
    private DiskType diskType;
    private String name;
    private Date releaseDate;

    @Id()
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "GROUP_ID", unique = true, nullable = false)
    public Integer getGroupId() {
        return this.groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DISK_CONTROLLER_ID", nullable = true)
    @NotFound(action = NotFoundAction.IGNORE)
    public DiskController getDiskController() {
        return this.diskController;
    }

    public void setDiskController(DiskController diskController) {
        this.diskController = diskController;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MANUFACTURER_ID", nullable = true)
    @NotFound(action = NotFoundAction.IGNORE)
    public Manufacturer getManufacturer() {
        return this.manufacturer;
    }

    public void setManufacturer(Manufacturer manufacturer) {
        this.manufacturer = manufacturer;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DISK_TYPE_ID", nullable = true)
    @NotFound(action = NotFoundAction.IGNORE)
    public DiskType getDiskType() {
        return this.diskType;
    }

    public void setDiskType(DiskType diskType) {
        this.diskType = diskType;
    }

    @Column(name = "NAME", nullable = false)
    @NotNull
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "release_date", nullable = true)
    public Date getReleaseDate() {
        return releaseDate;
    }

    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

}
