package be.colardyn_it.model;

// Generated Apr 14, 2009 1:43:35 PM by Hibernate Tools 3.2.2.GA


import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.ToString;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * MbModel generated by hbm2java
 */
@Entity
@Table(name = "disk_type")
@Builder
@ToString
@AllArgsConstructor
@NoArgsConstructor
public class DiskType implements java.io.Serializable {

    private Integer diskTypeId;
    private String name;

    @Id()
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "DISK_TYPE_ID", unique = true, nullable = false)
    public Integer getDiskTypeId() {
        return this.diskTypeId;
    }

    public void setDiskTypeId(Integer diskTypeId) {
        this.diskTypeId = diskTypeId;
    }

    @Column(name = "NAME", nullable = false)
    @NotNull
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
