package be.colardyn_it.model;

// Generated Apr 8, 2009 11:16:30 AM by Hibernate Tools 3.2.2.GA

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.ToString;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;
import org.hibernate.annotations.Type;
import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * GpuCore generated by hbm2java
 */
@Entity
@Table(name = "gpu_core", uniqueConstraints = @UniqueConstraint(columnNames = "CODENAME"))
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = {"gpuModels","gpuFamily"})
public class GpuCore implements java.io.Serializable {

    private Integer coreId;
    private GpuFamily gpuFamily;
    private Integer directxId;
    private Integer openglId;
    private String codename;
    private BigDecimal shaderModel;
    private BigDecimal voltage;
    private BigDecimal manufacturingProcess;
    private Set<GpuModel> gpuModels = new HashSet<GpuModel>(0);

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "CORE_ID", unique = true, nullable = false)
    public Integer getCoreId() {
        return this.coreId;
    }

    public void setCoreId(Integer coreId) {
        this.coreId = coreId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "FAMILY_ID", nullable = false)
    @NotNull
    @NotFound(action = NotFoundAction.IGNORE)
    public GpuFamily getGpuFamily() {
        return this.gpuFamily;
    }

    public void setGpuFamily(GpuFamily gpuFamily) {
        this.gpuFamily = gpuFamily;
    }

    @Column(name = "DIRECTX_ID")
    public Integer getDirectxId() {
        return this.directxId;
    }

    public void setDirectxId(Integer directxId) {
        this.directxId = directxId;
    }

    @Column(name = "OPENGL_ID")
    public Integer getOpenglId() {
        return this.openglId;
    }

    public void setOpenglId(Integer openglId) {
        this.openglId = openglId;
    }

    @Column(name = "CODENAME", unique = true, length = 50)
    @Length(max = 50)
    public String getCodename() {
        return this.codename;
    }

    public void setCodename(String codename) {
        this.codename = codename;
    }

    @Column(name = "SHADER_MODEL", precision = 3, scale = 1)
    public BigDecimal getShaderModel() {
        return this.shaderModel;
    }

    public void setShaderModel(BigDecimal shaderModel) {
        this.shaderModel = shaderModel;
    }

    @Column(name = "VOLTAGE", precision = 3)
    public BigDecimal getVoltage() {
        return this.voltage;
    }

    public void setVoltage(BigDecimal voltage) {
        this.voltage = voltage;
    }

    @Column(name = "MANUFACTURING_PROCESS", precision = 4, scale = 3)
    @Type(type = "big_decimal")
    public BigDecimal getManufacturingProcess() {
        return this.manufacturingProcess;
    }

    public void setManufacturingProcess(BigDecimal manufacturingProcess) {
        this.manufacturingProcess = manufacturingProcess;
    }

    @OneToMany(cascade = {CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH}, fetch = FetchType.LAZY, mappedBy = "gpuCore")
    public Set<GpuModel> getGpuModels() {
        return this.gpuModels;
    }

    public void setGpuModels(Set<GpuModel> gpuModels) {
        this.gpuModels = gpuModels;
    }

}
