package be.colardyn_it.model;

// Generated Apr 8, 2009 11:16:30 AM by Hibernate Tools 3.2.2.GA

import be.colardyn_it.util.StringUtil;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;
import org.hibernate.annotations.Type;
import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * GpuModel generated by hbm2java
 */
@Entity
@Table(name = "gpu_model", uniqueConstraints = @UniqueConstraint(columnNames = "MODEL"))
public class GpuModel implements java.io.Serializable {

    private Integer gpuId;
    private Socket socket;
    private Memory memory;
    private GpuCore gpuCore;
    private int cores;
    private String keywords;
    private String model;
    private Integer coreSpeed;
    private Integer memSpeed;
    private Integer memBus;
    private Integer memSize;
    private String pipelines;
    private String vertexShaders;
    private Boolean sliCapable;
    private Boolean marked;
    private Integer heat;
    private String rop;
    private String streamProcessors;
    private String safeName;
    private Date releaseDate;

    public GpuModel() {
    }

    public GpuModel(GpuCore gpuCore, int cores, String model, Boolean sliCapable, Boolean marked) {
        this.gpuCore = gpuCore;
        this.cores = cores;
        this.model = model;
        this.sliCapable = sliCapable;
        this.marked = marked;
    }

    public GpuModel(Socket socket, Memory memory, GpuCore gpuCore, int cores, String keywords, String model, Integer coreSpeed, Integer memSpeed, Integer memBus,
                    Integer memSize, String pipelines, String vertexShaders, Boolean sliCapable, Boolean marked, Integer heat, String rop, String streamProcessors) {
        this.socket = socket;
        this.memory = memory;
        this.gpuCore = gpuCore;
        this.cores = cores;
        this.keywords = keywords;
        this.model = model;
        this.coreSpeed = coreSpeed;
        this.memSpeed = memSpeed;
        this.memBus = memBus;
        this.memSize = memSize;
        this.pipelines = pipelines;
        this.vertexShaders = vertexShaders;
        this.sliCapable = sliCapable;
        this.marked = marked;
        this.heat = heat;
        this.rop = rop;
        this.streamProcessors = streamProcessors;
    }

    @PrePersist
    @PreUpdate
    public void checkSafeName() {
        this.safeName = StringUtil.makeUrlSafe(model);
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "GPU_ID", unique = true, nullable = false)
    public Integer getGpuId() {
        return this.gpuId;
    }

    public void setGpuId(Integer gpuId) {
        this.gpuId = gpuId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SOCKET_ID")
    @NotFound(action = NotFoundAction.IGNORE)
    public Socket getSocket() {
        return this.socket;
    }

    public void setSocket(Socket socket) {
        this.socket = socket;
    }

    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumn(name = "MEM_ID")
    @NotFound(action = NotFoundAction.IGNORE)
    public Memory getMemory() {
        return this.memory;
    }

    public void setMemory(Memory memory) {
        this.memory = memory;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CORE_ID", nullable = false)
    @NotNull
    @NotFound(action = NotFoundAction.IGNORE)
    public GpuCore getGpuCore() {
        return this.gpuCore;
    }

    public void setGpuCore(GpuCore gpuCore) {
        this.gpuCore = gpuCore;
    }

    @Column(name = "CORES", nullable = false)
    @NotNull
    public int getCores() {
        return this.cores;
    }

    public void setCores(int cores) {
        this.cores = cores;
    }

    @Column(name = "KEYWORDS", length = 50)
    @Length(max = 50)
    public String getKeywords() {
        return this.keywords;
    }

    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    @Column(name = "MODEL", unique = true, nullable = false, length = 50)
    @NotNull
    @Length(max = 50)
    public String getModel() {
        return this.model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    @Column(name = "CORE_SPEED", precision = 4, scale = 0)
    public Integer getCoreSpeed() {
        return this.coreSpeed;
    }

    public void setCoreSpeed(Integer coreSpeed) {
        this.coreSpeed = coreSpeed;
    }

    @Column(name = "MEM_SPEED", precision = 4, scale = 0)
    public Integer getMemSpeed() {
        return this.memSpeed;
    }

    public void setMemSpeed(Integer memSpeed) {
        this.memSpeed = memSpeed;
    }

    @Column(name = "MEM_BUS", precision = 4, scale = 0)
    public Integer getMemBus() {
        return this.memBus;
    }

    public void setMemBus(Integer memBus) {
        this.memBus = memBus;
    }

    @Column(name = "MEM_SIZE", precision = 4, scale = 0)
    public Integer getMemSize() {
        return this.memSize;
    }

    public void setMemSize(Integer memSize) {
        this.memSize = memSize;
    }

    @Column(name = "PIPELINES", length = 20)
    @Length(max = 20)
    public String getPipelines() {
        return this.pipelines;
    }

    public void setPipelines(String pipelines) {
        this.pipelines = pipelines;
    }

    @Column(name = "VERTEX_SHADERS", length = 20)
    @Length(max = 20)
    public String getVertexShaders() {
        return this.vertexShaders;
    }

    public void setVertexShaders(String vertexShaders) {
        this.vertexShaders = vertexShaders;
    }

    @Column(name = "SLI_CAPABLE", nullable = false)
    @Type(type = "yes_no")
    @NotNull
    public Boolean getSliCapable() {
        return this.sliCapable;
    }

    public void setSliCapable(Boolean sliCapable) {
        this.sliCapable = sliCapable;
    }

    @Column(name = "MARKED", nullable = false)
    @NotNull
    @Type(type = "yes_no")
    public Boolean getMarked() {
        return this.marked;
    }

    public void setMarked(Boolean marked) {
        this.marked = marked;
    }

    @Column(name = "HEAT", precision = 4, scale = 0)
    public Integer getHeat() {
        return this.heat;
    }

    public void setHeat(Integer heat) {
        this.heat = heat;
    }

    @Column(name = "ROP", length = 20)
    @Length(max = 20)
    public String getRop() {
        return this.rop;
    }

    public void setRop(String rop) {
        this.rop = rop;
    }

    @Column(name = "STREAM_PROCESSORS", length = 20)
    @Length(max = 20)
    public String getStreamProcessors() {
        return this.streamProcessors;
    }

    public void setStreamProcessors(String streamProcessors) {
        this.streamProcessors = streamProcessors;
    }

    @Column(name = "SAFE_NAME", nullable = false, length = 50)
    @NotNull
    @Length(max = 50)
    public String getSafeName() {
        return this.safeName;
    }

    public void setSafeName(String model) {
        this.safeName = model;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "release_date", nullable = true)
    public Date getReleaseDate() {
        return releaseDate;
    }

    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

}
