package be.colardyn_it.model;

// Generated Apr 8, 2009 11:16:30 AM by Hibernate Tools 3.2.2.GA


import be.colardyn_it.util.StringUtil;
import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * GpuName generated by hbm2java
 */
@Entity
@Table(name = "gpu_product", uniqueConstraints = @UniqueConstraint(columnNames = "NAME"))
public class GpuProduct implements java.io.Serializable {

    private Integer gpuProductId;
    private Memory memory;
    private Manufacturer manufacturer;
    private GpuModel gpuModel;
    private Integer coreSpeed;
    private Integer memSpeed;
    private Integer shaderSpeed;
    private Integer memBus;
    private Integer memSize;
    private String safeName;
    private String name;


    public GpuProduct(Manufacturer manufacturer, GpuModel gpuModel, String name) {
        this.manufacturer = manufacturer;
        this.gpuModel = gpuModel;
        this.name = name;
    }

    public GpuProduct() {
    }

    @PrePersist
    @PreUpdate
    public void checkSafeName() {
        this.safeName = StringUtil.makeUrlSafe(name);
    }


    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "GPU_PRODUCT_ID", unique = true, nullable = false)
    public Integer getGpuProductId() {
        return this.gpuProductId;
    }

    public void setGpuProductId(Integer gpuId) {
        this.gpuProductId = gpuId;
    }

    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumn(name = "MEM_ID")
    public Memory getMemory() {
        return this.memory;
    }

    public void setMemory(Memory memory) {
        this.memory = memory;
    }

    @Column(name = "NAME", unique = true, nullable = false, length = 50)
    @NotNull
    @Length(max = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String model) {
        this.name = model;
    }

    @Column(name = "CORE_SPEED", precision = 4, scale = 0)
    public Integer getCoreSpeed() {
        return this.coreSpeed;
    }

    public void setCoreSpeed(Integer coreSpeed) {
        this.coreSpeed = coreSpeed;
    }

    @Column(name = "SHADER_SPEED", precision = 4, scale = 0)
    public Integer getShaderSpeed() {
        return this.shaderSpeed;
    }

    public void setShaderSpeed(Integer shaderSpeed) {
        this.shaderSpeed = shaderSpeed;
    }

    @Column(name = "MEM_SPEED", precision = 4, scale = 0)
    public Integer getMemSpeed() {
        return this.memSpeed;
    }

    public void setMemSpeed(Integer memSpeed) {
        this.memSpeed = memSpeed;
    }

    @Column(name = "MEM_BUS", precision = 4, scale = 0)
    public Integer getMemBus() {
        return this.memBus;
    }

    public void setMemBus(Integer memBus) {
        this.memBus = memBus;
    }

    @Column(name = "MEM_SIZE", precision = 4, scale = 0)
    public Integer getMemSize() {
        return this.memSize;
    }

    public void setMemSize(Integer memSize) {
        this.memSize = memSize;
    }

    @Column(name = "SAFE_NAME", nullable = false, length = 50)
    @NotNull
    @Length(max = 50)
    public String getSafeName() {
        return this.safeName;
    }

    public void setSafeName(String model) {
        this.safeName = model;
    }

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "MANUFACTURER_ID")
    public Manufacturer getManufacturer() {
        return manufacturer;
    }

    public void setManufacturer(Manufacturer manufacturer) {
        this.manufacturer = manufacturer;
    }

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "GPU_ID")
    public GpuModel getGpuModel() {
        return gpuModel;
    }

    public void setGpuModel(GpuModel gpuModel) {
        this.gpuModel = gpuModel;
    }

}
