package be.colardyn_it.model;

// Generated Apr 14, 2009 1:43:35 PM by Hibernate Tools 3.2.2.GA

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;
import org.hibernate.annotations.Type;
import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Manufacturer generated by hbm2java
 */
@Entity
@Table(name = "manufacturer", uniqueConstraints = @UniqueConstraint(columnNames = "NAME"))
public class Manufacturer implements java.io.Serializable {

    private Integer manufacturerId;
    private String name;
    private String color;
    private String website;
    private Boolean visible;
    private String description;
    private Set<MbModel> mbModels = new HashSet<MbModel>(0);
    private Set<MbChipset> mbChipsets = new HashSet<MbChipset>(0);

    public Manufacturer() {
    }

    public Manufacturer(String name, String color, Boolean visible) {
        this.name = name;
        this.color = color;
        this.visible = visible;
    }

    public Manufacturer(String name, String color, String website, Boolean visible, Set<MbModel> mbModels,
                        Set<MbChipset> mbChipsets) {
        this.name = name;
        this.color = color;
        this.website = website;
        this.visible = visible;
        this.mbModels = mbModels;
        this.mbChipsets = mbChipsets;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "MANUFACTURER_ID", unique = true, nullable = false)
    public Integer getManufacturerId() {
        return this.manufacturerId;
    }

    public void setManufacturerId(Integer manufacturerId) {
        this.manufacturerId = manufacturerId;
    }

    @Column(name = "NAME", unique = true, nullable = false, length = 50)
    @NotNull
    @Length(max = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "COLOR", nullable = false, length = 7)
    @NotNull
    @Length(max = 7)
    public String getColor() {
        return this.color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    @Column(name = "WEBSITE", length = 100)
    @Length(max = 100)
    public String getWebsite() {
        return this.website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    @Column(name = "VISIBLE", nullable = false)
    @NotNull
    @Type(type = "yes_no")
    public Boolean getVisible() {
        return this.visible;
    }

    public void setVisible(Boolean visible) {
        this.visible = visible;
    }


    @OneToMany(cascade = {CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH}, fetch = FetchType.LAZY, mappedBy = "manufacturer")
    @NotFound(action = NotFoundAction.IGNORE)
    public Set<MbModel> getMbModels() {
        return this.mbModels;
    }

    public void setMbModels(Set<MbModel> mbModels) {
        this.mbModels = mbModels;
    }

    @OneToMany(cascade = {CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH}, fetch = FetchType.LAZY, mappedBy = "manufacturer")
    @NotFound(action = NotFoundAction.IGNORE)
    public Set<MbChipset> getMbChipsets() {
        return this.mbChipsets;
    }

    public void setMbChipsets(Set<MbChipset> mbChipsets) {
        this.mbChipsets = mbChipsets;
    }

    @Column(columnDefinition = "longtext")
    @Lob
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
