package be.colardyn_it.model;

// Generated Apr 8, 2009 11:16:30 AM by Hibernate Tools 3.2.2.GA

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.ToString;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;
import org.hibernate.annotations.Type;
import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Memoryrating generated by hbm2java
 */
@Entity
@Table(name = "memoryrating", uniqueConstraints = @UniqueConstraint(columnNames = "NAME"))
@Builder
@ToString(doNotUseGetters = true)
@AllArgsConstructor
@NoArgsConstructor
public class Memoryrating implements java.io.Serializable {

    private Integer memratingId;
    private Memory memory;
    private String name;
    private Boolean visible = true;

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "MEMRATING_ID", unique = true, nullable = false)
    public Integer getMemratingId() {
        return this.memratingId;
    }

    public void setMemratingId(Integer memratingId) {
        this.memratingId = memratingId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MEM_ID", nullable = false)
    @NotNull
    @NotFound(action = NotFoundAction.IGNORE)
    public Memory getMemory() {
        return this.memory;
    }

    public void setMemory(Memory memory) {
        this.memory = memory;
    }

    @Column(name = "NAME", unique = true, nullable = false, length = 20)
    @NotNull
    @Length(max = 20)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "VISIBLE", nullable = false)
    @NotNull
    @Type(type = "yes_no")
    public Boolean getVisible() {
        return this.visible;
    }

    public void setVisible(Boolean visible) {
        this.visible = visible;
    }

}
