package be.colardyn_it.model;

// Generated Apr 8, 2009 11:16:30 AM by Hibernate Tools 3.2.2.GA

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.ToString;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;
import org.hibernate.annotations.Type;
import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * GpuName generated by hbm2java
 */
@Entity
@Table(name = "memoryproductgroup", uniqueConstraints = @UniqueConstraint(columnNames = "label"))
@Builder
@ToString(exclude = {"manufacturer"})
@AllArgsConstructor
@NoArgsConstructor
public class MemoryProduct implements java.io.Serializable {

    private Integer memproductgroupId;
    private Manufacturer manufacturer;
    private String label;
    private Boolean visible = true;
    private Date releaseDate;

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "MEMPRODUCTGROUP_ID", unique = true, nullable = false)
    public Integer getMemproductgroupId() {
        return this.memproductgroupId;
    }

    public void setMemproductgroupId(Integer memproductgroupId) {
        this.memproductgroupId = memproductgroupId;
    }

    @Column(name = "LABEL", unique = true, nullable = false, length = 50)
    @NotNull
    @Length(max = 50)
    public String getLabel() {
        return this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "MANUFACTURER_ID")
    @NotFound(action = NotFoundAction.IGNORE)
    public Manufacturer getManufacturer() {
        return manufacturer;
    }

    public void setManufacturer(Manufacturer manufacturer) {
        this.manufacturer = manufacturer;
    }

    @Column(name = "VISIBLE", nullable = false)
    @NotNull
    @Type(type = "yes_no")
    public Boolean getVisible() {
        return this.visible;
    }

    public void setVisible(Boolean visible) {
        this.visible = visible;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "release_date", nullable = true)
    public Date getReleaseDate() {
        return releaseDate;
    }

    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

}
