package be.colardyn_it.model;

// Generated Apr 14, 2009 1:32:23 PM by Hibernate Tools 3.2.2.GA


import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Opengl generated by hbm2java
 */
@Entity
@Table(name = "opengl", uniqueConstraints = @UniqueConstraint(columnNames = "NAME"))
public class Opengl implements java.io.Serializable {

    private Integer openglId;
    private String name;

    public Opengl() {
    }

    public Opengl(String name) {
        this.name = name;
    }

    public Opengl(Integer descriptionId, String name) {
        this.name = name;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "OPENGL_ID", unique = true, nullable = false)
    public Integer getOpenglId() {
        return this.openglId;
    }

    public void setOpenglId(Integer openglId) {
        this.openglId = openglId;
    }

    @Column(name = "NAME", unique = true, nullable = false, length = 30)
    @NotNull
    @Length(max = 30)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
