package be.colardyn_it.enums;

public enum RankingType {

    CPU, CPUCORE, CPUCORECOUNT, CPUSOCKET, CPUSUBFAMILY,
    GPU, GPUFAMILY, GPUCORE, GPUSOCKET, GPUSOCKETCATEGORY,
    MBMODEL, MEM, MBCHIPSET, PSU, DISK, SOCKET

}
